name: Deploy to GitHub pages
on:
  push:
    # this is the branch where you develop your site
    # as discussed in the publishing sources section
    # this can change if you are using an user/organization repo
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v4.0.4
      with: 
        node_version: '18'
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - name: Build site
      uses: borales/actions-yarn@v4
      with:
        cmd: si:build
    - name: Move site
      uses: borales/actions-yarn@v4
      with:
        cmd: gh-mv-docs
    - name: Git Auto Commit
      # You may pin to the exact commit or the version.
      # uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842
      uses: stefanzweifel/git-auto-commit-action@v5.0.1
      with:
        # Commit message
        commit_message: site publish
        # Git branch name, where changes should be pushed too. Required if Action is used on the `pull_request` event
        branch: gh-test
        # Push options (eg. --force)
        push_options: --force
        # Create new branch with the name of `branch`-input in local and remote repository, if it doesn't exist yet.
        create_branch: true          
    # - name: GitHub Push
    #   # You may pin to the exact commit or the version.
    #   # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
    #   uses: ad-m/github-push-action@v0.6.0
    #   with:
    #     # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     # Destination branch to push changes
    #     branch: gh-test
          
